name: "Ritar BMS"
description: "Ritar BAT-5KWH-51.2V Battery BMS Logger"
version: "1.8.4"
slug: "ritar_bms"
url: "https://github.com/mamontuka/ritar-bms-ha"
init: false
uart: true
usb: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
options:
  connection_type: ethernet
  rs485gate_ip: "192.168.0.100"
  rs485gate_port: 50500
  serial_port: "/dev/ttyUSB0"
  serial_baudrate: 9600
  connection_timeout: 3
  queries_delay: 0.1
  battery_model: BAT-5KWH-51.2V
  num_batteries: 1
  next_battery_delay : 0.5
  read_timeout: 15
  mqtt_broker: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: "homeassistant"
  mqtt_password: "mqtt_password_here"
schema:
  connection_type: list(ethernet|serial)
  rs485gate_ip: str
  rs485gate_port: int
  serial_port: str
  serial_baudrate: int
  connection_timeout: int
  queries_delay: float
  battery_model: list(BAT-5KWH-51.2V|BAT-10KWH-51.2V|BAT-15KWH-51.2V)
  num_batteries: int
  next_battery_delay: float
  read_timeout: int
  mqtt_broker: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: password
