name: "Ritar BMS"
description: "Ritar BAT-5KWH-51.2V Battery BMS Logger"
version: "1.2"
slug: "ritar_bms"
url: "https://github.com/mamontuka/ritar-bms-ha"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
   50501/tcp: 50501
options:
  rs485gate_ip: "192.168.0.100"
  rs485gate_port: 50500
  num_batteries: 1
  read_timeout: 30
#  debug: true
schema:
  rs485gate_ip: str
  rs485gate_port: int
  num_batteries: int
#  debug: bool
  read_timeout: int
