name: "Ritar BMS"
description: "Ritar BAT-5KWH-51.2V Battery BMS Logger"
version: "1.5"
slug: "ritar_bms"
url: "https://github.com/mamontuka/ritar-bms-ha"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
   50501/tcp: 50501
options:
  rs485gate_ip: "192.168.0.100"
  rs485gate_port: 50500
  connection_timeout: 3
  queries_delay: 0.1
  extra_queries_delay: 0.1
  num_batteries: 1
  next_battery_delay : 0.5
  read_timeout: 30
#  debug: true
schema:
  rs485gate_ip: str
  rs485gate_port: int
  connection_timeout: int
  queries_delay: float
  extra_queries_delay: float
  num_batteries: int
  next_battery_delay: float
  read_timeout: int
#  debug: bool
