version: '3'
services:
  ritar-bms:
    build: 
      context: .
    restart: unless-stopped
    privileged: true
    ports:
      - "2222:2222"
    volumes:
      - ./config.yaml:/united_bms_core/config.yaml
      - ${PWD}/united_bms:/united_bms
      - /dev:/dev
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
